### ISSUE TITLE
request help: failed to connect to the unix socket unix:/usr/local/apisix/conf/apisix-1.sock

### ISSUE THREAD

**Issue by kamyam** [apache/apisix-java-plugin-runner#224]
### Issue description
1. java-plugin，When I do not configure socket.file ，An error will be reported at startup

If I configure socket.file=/usr/local/apisix/conf/runner.sock starting success，but apisix find the unix:/usr/local/apisix/conf/apisix-1.sock:

Caused by: java.lang.IllegalArgumentException: Could not resolve placeholder 'socket.file' in value "${socket.file}"
	at org.springframework.util.PropertyPlaceholderHelper.parseStringValue(PropertyPlaceholderHelper.java:180) ~[spring-core-5.3.22.jar:5.3.22]
	at org.springframework.util.PropertyPlaceholderHelper.replacePlaceholders(PropertyPlaceholderHelper.java:126) ~[spring-core-5.3.22.jar:5.3.22]
	at org.springframework.core.env.AbstractPropertyResolver.doResolvePlaceholders(AbstractPropertyResolver.java:239) ~[spring-core-5.3.22.jar:5.3.22]
	at org.springframework.core.env.AbstractPropertyResolver.resolveRequiredPlaceholders(AbstractPropertyResolver.java:210) ~[spring-core-5.3.22.jar:5.3.22]
	at org.springframework.context.support.PropertySourcesPlaceholderConfigurer.lambda$processProperties$0(PropertySourcesPlaceholderConfigurer.java:191) ~[spring-context-5.3.22.jar:5.3.22]
	at org.springframework.beans.factory.support.AbstractBeanFactory.resolveEmbeddedValue(AbstractBeanFactory.java:936) ~[spring-beans-5.3.22.jar:5.3.22]
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.doResolveDependency(DefaultListableBeanFactory.java:1332) ~[spring-beans-5.3.22.jar:5.3.22]
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.resolveDependency(DefaultListableBeanFactory.java:1311) ~[spring-beans-5.3.22.jar:5.3.22]

### Environment

* your apisix-java-plugin-runner 0.4.0

**Comment by kamyam** [comment]
socket.file must be equal to /usr/local/apisix/conf/apisix-1.sock？？

**Comment by kamyam** [comment]
socket:
  file: ${APISIX_LISTEN_ADDRESS}
