### ISSUE TITLE
request help: apisix-java-plugin-runner start error:Caused by: io.netty.channel.unix.Errors$NativeIoException: bind(..) failed: No such file or directory

### ISSUE THREAD

**Issue by jimmystrong** [apache/apisix-java-plugin-runner#277]
### Issue description
when I started apisix java plugin runner by apisix, i got following errors. It's good when I use debug mode in apisix and the plugin runner. I tried to search answers but no found for a whole day. And I really need to solve this. Somebody who could help me out? Many thanks!

2023/11/24 10:21:40 [warn] 25144#25144: *85 [lua] init.lua:961: 2023-11-24 10:21:40.909 ERROR 25205 --- [           main] o.s.b.SpringApplication                  : Application run failed

java.lang.IllegalStateException: Failed to execute CommandLineRunner
        at org.springframework.boot.SpringApplication.callRunner(SpringApplication.java:785) [spring-boot-2.6.8.jar!/:2.6.8]
        at org.springframework.boot.SpringApplication.callRunners(SpringApplication.java:766) [spring-boot-2.6.8.jar!/:2.6.8]
        at org.springframework.boot.SpringApplication.run(SpringApplication.java:314) [spring-boot-2.6.8.jar!/:2.6.8]
        at org.springframework.boot.builder.SpringApplicationBuilder.run(SpringApplicationBuilder.java:164) [spring-boot-2.6.8.jar!/:2.6.8]
        at org.apache.apisix.plugin.runner.PluginRunnerApplication.main(PluginRunnerApplication.java:38) [classes!/:0.4.0]
        at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
        at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77) ~[?:?]
        at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
        at java.lang.reflect.Method.invoke(Method.java:568) ~[?:?]
        at org.springframework.boot.loader.MainMethodRunner.run(MainMethodRunner.java:49) [apisix-java-plugin-runner.jar:0.4.0]
        at org.springframework.boot.loader.Launcher.launch(Launcher.java:108) [apisix-java-plugin-runner.jar:0.4.0]
        at org.springframework.boot.loader.Launcher.launch(Launcher.java:58) [apisix-java-plugin-runner.jar:0.4.0]
        at org.springframework.boot.loader.PropertiesLauncher.main(PropertiesLauncher.java:467) [apisix-java-plugin-runner.jar:0.4.0]
Caused by: io.netty.channel.unix.Errors$NativeIoException: bind(..) failed: No such file or directory

, context: ngx.timer
2023/11/24 10:21:40 [warn] 25144#25144: *85 [lua] init.lua:967: runner exited with reason: exit, status: 1, context: ngx.timer
2023/11/24 10:21:40 [warn] 25144#25144: *85 [lua] init.lua:387: flush_token(): flush conf token in shared dict, context: ngx.timer

apisix config:
ext-plugin: 
  #path_for_test: /tmp/runner.sock
  cmd: ['/opt/apps/java/jdk-17.0.8/bin/java','-jar','/opt/apps/apisix-plugin/apisix-runner-bin/apisix-java-plugin-runner.jar']

### Environment
apisix version: 3.6.0
* your apisix-java-plugin-runner version: 0.4.0

**Comment by yijieshusheng-git** [comment]
check youe config.yaml you can read this: https://github.com/apache/apisix/issues/10649#issue-2039958787
