### ISSUE TITLE
bug: Java pulugin ruuner filter get config occured java.lang.IndexOutOfBoundsException: null

### ISSUE THREAD

**Issue by seominho77** [apache/apisix-java-plugin-runner#63]
### When user HttpRequest.getConfig get config some times occured java.lang.IndexOutOfBoundsException: null
java 插件获取配置信息是出现异常，刚开始时正常，过一会儿就开始经常出现此异常。
### Environment 

* your apisix-java-plugin-runner version 2.8

### Minimal test code / Steps to reproduce the issue
String configStr = request.getConfig(this);

### What's the actual result? (including assertion message & call stack if applicable)
error info:
java.lang.IndexOutOfBoundsException: null
        at java.nio.Buffer.checkIndex(Buffer.java:551) ~[?:1.8.0_292]
        at java.nio.DirectByteBuffer.getInt(DirectByteBuffer.java:684) ~[?:1.8.0_292]
        at com.google.flatbuffers.Table.__reset(Table.java:301) ~[flatbuffers-java-1.12.0.jar!/:?]
        at io.github.api7.A6.TextEntry.__init(TextEntry.java:15) ~[A6-0.1.0-RELEASE.jar!/:?]
        at io.github.api7.A6.TextEntry.__assign(TextEntry.java:16) ~[A6-0.1.0-RELEASE.jar!/:?]
        at io.github.api7.A6.PrepareConf.Req.conf(Req.java:19) ~[A6-0.1.0-RELEASE.jar!/:?]
        at io.github.api7.A6.PrepareConf.Req.conf(Req.java:18) ~[A6-0.1.0-RELEASE.jar!/:?]
        at org.apache.apisix.plugin.runner.HttpRequest.getConfig(HttpRequest.java:62) ~[apisix-runner-plugin-sdk-0.1.0.jar!/:0.1.0]
        at org.apache.apisix.plugin.runner.filter.LoginAuthFilter.filter(LoginAuthFilter.java:46) ~[apisix-runner-plugin-0.1.0.jar!/:0.1.0]
        at org.apache.apisix.plugin.runner.filter.PluginFilterChain.filter(PluginFilterChain.java:54) ~[apisix-runner-plugin-sdk-0.1.0.jar!/:0.1.0]
        at org.apache.apisix.plugin.runner.handler.A6HttpCallHandler.handle(A6HttpCallHandler.java:57) ~[apisix-runner-core-0.1.0.jar!/:0.1.0]
        at org.apache.apisix.plugin.runner.handler.A6HandlerConfiguration.lambda$createDispatcher$0(A6HandlerConfiguration.java:76) ~[apisix-runner-core-0.1.0.jar!/:0.1.0]
        at reactor.core.publisher.FluxMap$MapSubscriber.onNext(FluxMap.java:106) [reactor-core-3.4.5.jar!/:3.4.5]
        at reactor.core.publisher.FluxMap$MapSubscriber.onNext(FluxMap.java:120) [reactor-core-3.4.5.jar!/:3.4.5]
        at reactor.core.publisher.FluxHandle$HandleSubscriber.onNext(FluxHandle.java:118) [reactor-core-3.4.5.jar!/:3.4.5]
        at reactor.core.publisher.FluxMap$MapConditionalSubscriber.onNext(FluxMap.java:220) [reactor-core-3.4.5.jar!/:3.4.5]
        at reactor.netty.channel.FluxReceive.drainReceiver(FluxReceive.java:280) [reactor-netty-core-1.0.6.jar!/:1.0.6]
        at reactor.netty.channel.FluxReceive.onInboundNext(FluxReceive.java:389) [reactor-netty-core-1.0.6.jar!/:1.0.6]
        at reactor.netty.channel.ChannelOperations.onInboundNext(ChannelOperations.java:401) [reactor-netty-core-1.0.6.jar!/:1.0.6]
        at reactor.netty.channel.ChannelOperationsHandler.channelRead(ChannelOperationsHandler.java:94) [reactor-netty-core-1.0.6.jar!/:1.0.6]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379) [netty-transport-4.1.63.Final.jar!/:4.1.63.Final]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365) [netty-transport-4.1.63.Final.jar!/:4.1.63.Final]
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357) [netty-transport-4.1.63.Final.jar!/:4.1.63.Final]
        at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:324) [netty-codec-4.1.63.Final.jar!/:4.1.63.Final]
        at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:296) [netty-codec-4.1.63.Final.jar!/:4.1.63.Final]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379) [netty-transport-4.1.63.Final.jar!/:4.1.63.Final]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365) [netty-transport-4.1.63.Final.jar!/:4.1.63.Final]
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357) [netty-transport-4.1.63.Final.jar!/:4.1.63.Final]
        at io.netty.handler.logging.LoggingHandler.channelRead(LoggingHandler.java:271) [netty-handler-4.1.63.Final.jar!/:4.1.63.Final]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannel, context: ngx.timer
2021/08/12 11:44:58 [warn] 1751#1751: *8209277 [lua] init.lua:617: HandlerContext.java:379) [netty-transport-4.1.63.Final.jar!/:4.1.63.Final]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365) [netty-transport-4.1.63.Final.jar!/:4.1.63.Final]
        at io.netty.channel.AbstractChannelHandlerContext.fireChannel, context: ngx.timer
2021/08/12 11:44:58 [warn] 1751#1751: *8209277 [lua] init.lua:617: Read(AbstractChannelHandlerContext.java:357) [netty-transport-4.1.63.Final.jar!/:4.1.63.Final]
        at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1410) [netty-transport-4.1.63.Final.jar!/:4.1.63.Final]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379) [netty-transport-4.1.63.Final.jar!/:4.1.63.Final]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365) [netty-transport-4.1.63.Final.jar!/:4.1.63.Final]
        at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:919) [netty-transport-4.1.63.Final.jar!/:4.1.63.Final]
        at io.netty.channel.epoll.AbstractEpollStreamChannel$EpollStreamUnsafe.epollInReady(AbstractEpollStreamChannel.java:795) [netty-transport-native-epoll-4.1.63.Final-linux-x86_64.jar!/:4.1.63.Final]
        at io.netty.channel.epoll.EpollDomainSocketChannel$EpollDomainUnsafe.epollInReady(EpollDomainSocketChannel.java:138) [netty-transport-native-epoll-4.1.63.Final-linux-x86_64.jar!/:4.1.63.Final]
        at io.netty.channel.epoll.EpollEventLoop.processReady(EpollEventLoop.java:480) [netty-transport-native-epoll-4.1.63.Final-linux-x86_64.jar!/:4.1.63.Final]
        at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:378) [netty-transport-native-epoll-4.1.63.Final-linux-x86_64.jar!/:4.1.63.Final]
        at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:989) [netty-common-4.1.63.Final.jar!/:4.1.63.Final]
        at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74) [netty-common-4.1.63.Final.jar!/:4.1.63.Final]
        at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30) [netty-common-4.1.63.Final.jar!/:4.1.63.Final]

**Comment by gxthrj** [comment]
cc @tzssangglass

**Comment by tzssangglass** [comment]
hi @seominho77, you need to show more reproducible info.

**Comment by tzssangglass** [comment]
What is your ext-plugin configuration on apisix?

**Comment by seominho77** [comment]
> What is your ext-plugin configuration on apisix?
"ext-plugin-post-req": {
      "conf": [
        {
          "name": "LoginAuthFilter",
          "value": "{\"auth_userinfo_endpoint\":\"http://10.7.1.14:10011/auth/platform/user\"}"
        }
      ]
    }

**Comment by seominho77** [comment]
> hi @seominho77, you need to show more reproducible info.

@tzssangglass   the same request sometiems is ok, sometimes occured this exception. After configuration(apisix reload),At first  it's all request is ok, but after a period of time the exception began to appear。

**Comment by tzssangglass** [comment]
I think the json escapes are wrong, take a look at: https://github.com/apache/apisix-java-plugin-runner/blob/df69b2ebd24860d2c9effc5aeaed6d1b7e8a176d/runner-core/src/test/java/org/apache/apisix/plugin/runner/handler/A6HttpCallHandlerTest.java#L129-L130

**Comment by seominho77** [comment]
"ext-plugin-post-req": {
      "conf": [
        {
          "name": "LoginAuthFilter",
          "value": "{\"auth_userinfo_endpoint\":\"http://10.7.1.14:10011/auth/platform/user\"}"
        }
      ]
    }
if the  json escapes are wrong， I think all requests should fail,but it's not all failed.

**Comment by seominho77** [comment]
"ext-plugin-post-req": {
      "conf": [
        {
          "name": "LoginAuthFilter",
          "value": "{\\"auth_userinfo_endpoint\\":\\"http://10.7.1.14:10011/auth/platform/user\\"}"
        }
      ]
    }
if the json escapes are wrong， I think all requests should fail,but it's not all failed.

**Comment by seominho77** [comment]
"ext-plugin-post-req": {
      "conf": [
        {
          "name": "LoginAuthFilter",
          "value": "{\"auth_userinfo_endpoint\":\"http://10.7.1.14:10011/auth/platform/user\"}"
        }
      ]
    }

if the json escapes are wrong, I think all requests should fail, but  not  all reques are failed

**Comment by tzssangglass** [comment]
Can you provide an example that uses the correct json escapes and reproduces them consistently?

**Comment by seominho77** [comment]
![image](https://user-images.githubusercontent.com/55071915/130742016-c54d1ca6-bf61-44cf-aad8-b4207acc0ce5.png)
plugin config is like this.
![image](https://user-images.githubusercontent.com/55071915/130741827-9d2989f7-0919-4972-b66b-897663dd6631.png)
this log , there is two same requset. first request throw this exception, but  second request is success.

**Comment by dongqisilent** [comment]
if the filter method     
`public Mono<Void> filter(HttpRequest request, HttpResponse response, PluginFilterChain chain) {`
throw RuntimeException, the exception will be swallow, and the next request go into the method with null.then throw the Exception, because the request is null now.
so you should try the Exception ,solve it

**Comment by tzssangglass** [comment]
I will check it later

**Comment by dongqisilent** [comment]
I find the same problem，then i find something when error happend；
watch com.google.common.cache.Cache getIfPresent '{params,returnObj,throwExp}'  -n 5  -x 3


Affect(class count: 3 , method count: 1) cost in 97 ms, listenerId: 5
method=com.google.common.cache.LocalCache$LocalManualCache.getIfPresent location=AtExit
ts=2021-09-01 19:43:49; [cost=0.078167ms] result=@ArrayList[
    @Object[][
        @Long[1399571776],
    ],
    @A6Conf[
        req=@Req[
            bb_pos=@Integer[12],
            bb=@DirectByteBuffer[java.nio.DirectByteBuffer[pos=0 lim=204 cap=204]],
            vtable_start=@Integer[4],
            vtable_size=@Integer[8],
            utf8=@Utf8Safe[com.google.flatbuffers.Utf8Safe@5c90c49b],
        ],
        **chain=@PluginFilterChain[
            index=@Integer[0],
            filters=@ArrayList[isEmpty=false;size=1],
        ],**
    ],
    null,
]

@tzssangglass

**Comment by tzssangglass** [comment]
> I find the same problem，then i find something when error happend；
> watch com.google.common.cache.Cache getIfPresent '{params,returnObj,throwExp}' -n 5 -x 3
> 
> Affect(class count: 3 , method count: 1) cost in 97 ms, listenerId: 5
> method=com.google.common.cache.LocalCache$LocalManualCache.getIfPresent location=AtExit
> ts=2021-09-01 19:43:49; [cost=0.078167ms] result=@Arraylist[
> @object[][
> @long[1399571776],
> ],
> @A6Conf[
> req=@Req[
> bb_pos=@integer[12],
> bb=@DirectByteBuffer[java.nio.DirectByteBuffer[pos=0 lim=204 cap=204]],
> vtable_start=@integer[4],
> vtable_size=@integer[8],
> utf8=@Utf8Safe[com.google.flatbuffers.Utf8Safe@5c90c49b],
> ],
> **chain=@PluginFilterChain[ index=@integer[0], filters=@Arraylist[isEmpty=false;size=1], ],**
> ],
> null,
> ]
> 
> @tzssangglass

What version of APISIX are you using?

**Comment by huang-x-h** [comment]
Now what's the progress?

**Comment by tzssangglass** [comment]
hi @seominho77 @dongqisilent @huang-x-h, fixed and can be verified with this PR: #66

**Comment by tzssangglass** [comment]
feel free to reopen this issue if you has problems

**Comment by huang-x-h** [comment]
Thanks, now it working fine 👍

**Comment by seominho77** [comment]
@tzssangglass  The exception occured again.  I have update runner-core code, and deploy apisix-java-plugin-runner.jar. about after 3 days, the exception occured,  and multiple concurrency is easy to occur(when my page load, send four request at the same time).

**Comment by seominho77** [comment]
@tzssangglass  The exception occured again.  I have update runner-core code, and deploy apisix-java-plugin-runner.jar. about after 3 days, the exception occured,  and multiple concurrency is easy to occur(when my page load, send four request at the same time).

**Comment by tzssangglass** [comment]
> @tzssangglass The exception occured again. I have update runner-core code, and deploy apisix-java-plugin-runner.jar. about after 3 days, the exception occured, and multiple concurrency is easy to occur(when my page load, send four request at the same time).

any error about this?

**Comment by seominho77** [comment]
> > @tzssangglass The exception occured again. I have update runner-core code, and deploy apisix-java-plugin-runner.jar. about after 3 days, the exception occured, and multiple concurrency is easy to occur(when my page load, send four request at the same time).
> 
> any error about this?


the same exception:
![image](https://user-images.githubusercontent.com/55071915/133540096-fee8c3d2-ce40-4133-af07-b35686561b35.png)
you can try concurrent requests, it's easy to occur.

**Comment by huang-x-h** [comment]
@tzssangglass can reopen the issue? the same exception is happened again 😭 

If we want to analyze the problem, can you give me an idea, Where are the problems?

**Comment by tzssangglass** [comment]
hi @huang-x-h @seominho77 , please use this PR to verify that it is fixed: #73

**Comment by huang-x-h** [comment]
@tzssangglass ok，we will try now

**Comment by Rdebu** [comment]
兄弟厉害啊 ， 我之前也有这情况，但是没查出来，昨天碰到了，受不了了提个issues

**Comment by Rdebu** [comment]
兄弟你是怎么打印报错日志的，只能catch后手动打印嘛
