### ISSUE TITLE
bug: HttpRequest.getConfig(this) raise  IndexOutOfBoundsException

### ISSUE THREAD

**Issue by cws1981** [apache/apisix-java-plugin-runner#93]
### Issue description
```
java.lang.IndexOutOfBoundsException: null
	at java.nio.Buffer.checkIndex(Buffer.java:550) ~[na:1.8.0_275]
	at java.nio.DirectByteBuffer.getInt(DirectByteBuffer.java:684) ~[na:1.8.0_275]
	at com.google.flatbuffers.Table.__vector_len(Table.java:125) ~[flatbuffers-java-1.12.0.jar!/:na]
	at io.github.api7.A6.PrepareConf.Req.confLength(Req.java:20) ~[A6-0.1.0-RELEASE.jar!/:na]
	at org.apache.apisix.plugin.runner.HttpRequest.getConfig(HttpRequest.java:61) ~[apisix-runner-plugin-sdk-0.1.0.jar!/:0.1.0]
	at org.apache.apisix.plugin.runner.filter.CheckTokenFilter.filter(CheckTokenFilter.java:47) ~[apisix-runner-plugin-0.1.0.jar!/:0.1.0]
	at org.apache.apisix.plugin.runner.filter.PluginFilterChain.filter(PluginFilterChain.java:54) [apisix-runner-plugin-sdk-0.1.0.jar!/:0.1.0]
	at org.apache.apisix.plugin.runner.handler.A6HttpCallHandler.handle(A6HttpCallHandler.java:57) [apisix-runner-core-0.1.0.jar!/:0.1.0]
	at org.apache.apisix.plugin.runner.handler.A6HandlerConfiguration.lambda$createDispatcher$0(A6HandlerConfiguration.java:76) [apisix-runner-core-0.1.0.jar!/:0.1.0]
	at reactor.core.publisher.FluxMap$MapSubscriber.onNext(FluxMap.java:106) ~[reactor-core-3.4.5.jar!/:3.4.5]
	at reactor.core.publisher.FluxMap$MapSubscriber.onNext(FluxMap.java:120) ~[reactor-core-3.4.5.jar!/:3.4.5]
	at reactor.core.publisher.FluxHandle$HandleSubscriber.onNext(FluxHandle.java:118) ~[reactor-core-3.4.5.jar!/:3.4.5]
```

### Environment

* your apisix-java-plugin-runner version 0.1.0

### Minimal test code / Steps to reproduce the issue

```
"ext-plugin-pre-req": {
      "conf": [
        {
          "name": "CheckTokenFilter",
          "value": "{\"public_key\":\"-----BEGIN PUBLIC KEY-----\nxxxx==\n-----END PUBLIC KEY-----\"}"
        }
      ]
    }
```
```java
String configStr = request.getConfig(this);
```

**Comment by tzssangglass** [comment]
pls use master branch to test

**Comment by tzssangglass** [comment]
no more response, considered as resolved, feel free to reopen this.
